### ISSUE TITLE
Problem building (MacOS, Homebrew)

### ISSUE THREAD

**Issue by MarinDeniaud** [g4edge/pyg4ometry#49] opened 2023-07-12 13:39 UTC
Appears to be a problem with cython but I don't know how to proceed

```
error: subprocess-exited-with-error
  
  × Building wheel for pyg4ometry (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      *** scikit-build-core 0.4.7 using CMake 3.26.4 (wheel)
      *** Configuring CMake...
      2023-07-12 14:22:46,319 - scikit_build_core - WARNING - libdir/ldlibrary: /opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/lib/Python.framework/Versions/3.11/Python is not a real file!
      loading initial cache file build/cpython-311/CMakeInit.txt
      -- Setting build type to 'Release'
      -- Found pybind11: /Users/marindeniaud/venv/py311-prod/lib/python3.11/site-packages/pybind11/include (found version "2.10.4")
      CMake Error at cmake/modules/FindCython.cmake:71 (message):
        Command
        "/private/var/folders/lw/jglsl8693f9_sllwxwgc2fjh0000gn/T/pip-build-env-8w5zpqob/overlay/bin/cython;--version"
        failed with output:
      
      Call Stack (most recent call first):
        CMakeLists.txt:34 (find_package)
      
      
      -- Using header-only CGAL
      -- Targetting Ninja
      -- Using /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ compiler.
      -- Running in macOS DARWIN_VERSION=22
      -- Found Boost: /opt/homebrew/lib/cmake/Boost-1.82.0/BoostConfig.cmake (found suitable version "1.82.0", minimum required is "1.66")
      -- Boost include dirs: /opt/homebrew/include
      -- Boost libraries:
      -- Found CGAL (found version "5.5.2")
      -- Found Boost: /opt/homebrew/lib/cmake/Boost-1.82.0/BoostConfig.cmake (found version "1.82.0")
      -- Found OpenCASCADE (found version "7.7.0")
      -- Configuring incomplete, errors occurred!
      
      *** CMake configuration failed
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyg4ometry
Failed to build pyg4ometry
ERROR: Could not build wheels for pyg4ometry, which is required to install pyproject.toml-based projects
```

**Comment by gipert** [comment] 2023-07-12 13:48
Hi, the issue is tracked in https://github.com/g4edge/pyg4ometry/issues/19, I just added some instructions there on how to get around it.

**Comment by gipert** [comment] 2023-07-12 17:53
Ok, I saw this already once on the GitHub MacOS runners:

https://github.com/g4edge/pyg4ometry/actions/runs/4732759192/jobs/8399328713#step:6:586

It somehow fixed by itself after some time. Seems related to a problem with the OCE installation, but I cannot reproduce it unfortunately since I don't have access to a MacOS machine. You could try upgrading/reinstalling the relevant Homebrew packages.

I'll keep this open, let me know if you figure it out!

**Comment by stewartboogert** [comment] 2023-07-12 17:59
I don’t see this on my Mac with homebrew. @MarinDeniaud can you attach a list of **all** your installed brew packages.

**Comment by gipert** [comment] 2023-07-12 18:02
FYI this is what we do to configure the MacOS runners:

https://github.com/g4edge/pyg4ometry/blob/5317f5b0d140416682c23469464cbbb68c51c8f1/.github/bin/install-deps-macos.sh#L3-L5

**Comment by stewartboogert** [comment] 2023-07-17 13:56
So the OpenCASCADE has an explicit version number to TBB 12.8 and brew version is now TBB 12.9. Can just link or copy the TBB files something like

``
cd /opt/homebrew/opt/tbb/lib
ln -s libtbb.12.9.dylib libtbb.12.9.dylib
ln -s libtbbmalloc.2.9.dylib libtbbmalloc.2.8.dylib
``

Thanks @lnevay

**Comment by MarinDeniaud** [comment] 2023-07-20 18:17
With the last changes in Stewart's last message we have been able to fix the installation. Thanks @gipert and @lnevay  for the help!

**Closed** 2023-07-20 21:50 UTC
